# Generated by Django 2.2.6 on 2019-11-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('fecha_reserva', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(help_text='agrega una breve descripción de tu sesión', max_length=1000)),
                ('tipo', models.CharField(blank=True, choices=[('B', 'Bebe'), ('S', 'Solo'), ('P', 'Parejas'), ('E', 'Evento'), ('O', 'Otro')], default='O', help_text='Tipo Sesión', max_length=1)),
            ],
            options={
                'ordering': ['fecha_reserva'],
            },
        ),
    ]
