# Generated by Django 2.2.6 on 2019-11-12 01:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fechas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaInstancia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Código único de reserva', primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, choices=[('r', 'Reservado'), ('d', 'Disponible')], default='d', help_text='Disponible', max_length=1)),
            ],
            options={
                'ordering': ['fecha_reserva'],
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={},
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_reserva',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='nombre',
        ),
        migrations.AddField(
            model_name='reserva',
            name='nombrecompleto',
            field=models.CharField(default=uuid.uuid4, help_text='Escribe tu nombre completo', max_length=500),
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='tipo',
        ),
        migrations.AddField(
            model_name='reserva',
            name='tipo',
            field=models.ManyToManyField(to='fechas.Tipo'),
        ),
    ]
