# Generated by Django 2.2.6 on 2019-11-12 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fechas', '0002_auto_20191111_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservainstancia',
            name='reserva',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fechas.Reserva'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='nombrecompleto',
            field=models.CharField(help_text='Escribe tu nombre completo', max_length=500),
        ),
    ]
