# Generated by Django 2.2.6 on 2019-11-12 02:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fechas', '0003_auto_20191111_2252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['fecha_reserva']},
        ),
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.CharField(blank=True, choices=[('r', 'Reservado'), ('d', 'Disponible')], default='d', help_text='Disponible', max_length=1),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Código único de reserva', primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='ReservaInstancia',
        ),
    ]
