# Generated by Django 2.2.6 on 2019-11-12 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fechas', '0004_auto_20191111_2305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={},
        ),
        migrations.CreateModel(
            name='ReservaInstancia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserva', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fechas.Reserva')),
            ],
        ),
    ]
