# Generated by Django 2.2.6 on 2019-11-12 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fechas', '0005_auto_20191111_2315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservainstancia',
            options={'ordering': ['estado']},
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='estado',
        ),
        migrations.AddField(
            model_name='reservainstancia',
            name='estado',
            field=models.CharField(blank=True, choices=[('r', 'Reservado'), ('d', 'Disponible')], default='d', help_text='Disponible', max_length=1),
        ),
        migrations.AlterField(
            model_name='reservainstancia',
            name='reserva',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fechas.Reserva'),
        ),
    ]
