# Generated by Django 2.2.6 on 2019-11-12 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fechas', '0006_auto_20191111_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservainstancia',
            name='reserva',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fechas.Reserva'),
        ),
    ]
