# Generated by Django 2.2.6 on 2019-11-12 16:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fechas', '0009_auto_20191112_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Código único de reserva', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reservainstancia',
            name='reserva',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fechas.Reserva'),
        ),
    ]
